# -*- coding: utf-8 -*-
"""python basic variables

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qjC2leT_evEin2HN7uqoE4tXjWGUr7pg
"""

1+2

a=10

a

sudh=456375

sudh

type(sudh)

type(a)

type(2)

s="pwskills"

type(s)

s1='this is my first python lecture'

s1

type(s1)

f=456.567

type(f)

c=5+6j

type(c)

c.real

c.imag

b=True

type(b)

b1=False

type(b1)

a1=45
a2=34

a1+a2

a1*a2

a1/a2

a1-a2

45/34

a1,a2=45,34

a,b,c,d=354,sudh,34.34,True

a

b

c

True

# Commented out IPython magic to ensure Python compatibility.
# %a=234

a=565467

a

b=bool(input())

b

type(b)

s="sudh"

s[1]

s[3]

s[100]

s[-1]

s[-4]

s[-345]

s1="pwskills"

s1[]

s1[0:2]

s1[2:7]

s1[2:800]

s1[2:]

s1[2:8]

s1[0:7:2]

s1[1:8:2]

s1[7:3:-1]

s1[-1:-5:-1]

s1[7:-9:-1]

s1[::-1]

s1[0]

a=10

a=20

a

s1[0]='s'

s1="swskills"

s1

s1[0]="p"

